Add styles to signup and signin views
BC-MAY-21-ROR/proyecto-final-proyecto-final-aug-21-team-01 pull request #60
Opened 2021-11-30 22:53 UTC by adrianMRJ

# Description
- What?: We've added styles to signup and login views
 - Why?: These changes were necesary for the visuals of the project.

  ## Screenshots
![Sign-up](https://user-images.githubusercontent.com/87874142/144141105-c4b79d27-c66b-4ffa-9694-b5714c958fb3.png)
![Sign-up (1)](https://user-images.githubusercontent.com/87874142/144141106-e95e5473-2173-46cc-b3df-697bda26ead8.png)
![Sign-in](https://user-images.githubusercontent.com/87874142/144141108-b7b00919-1fba-468c-bd5a-0d0c41ff30d0.png)
![Sign-in (1)](https://user-images.githubusercontent.com/87874142/144141111-a8f04172-ecce-461f-983f-7e3b14300a19.png)

2021-11-30 23:03 UTC, JuanequeX requested changes

2021-11-30 23:03 UTC, JuanequeX commented on stylesheets/application/objects/buttons.scss
> +}
Add blank line here

2021-11-30 23:03 UTC, JuanequeX commented on stylesheets/application/objects/inputs.scss
> +}
Add blank line here

2021-11-30 23:03 UTC, JuanequeX commented on stylesheets/application/objects/labels.scss
> +}
Add blank line here

2021-11-30 23:03 UTC, JuanequeX commented on stylesheets/application/objects/labels.scss
> +}
And modify this identation

2021-11-30 23:03 UTC, JuanequeX commented on stylesheets/application/typography.scss
> +}
Add blank line here

2021-11-30 23:03 UTC, JuanequeX commented on stylesheets/application/objects/inputs.scss
> +}
And modify this identation

2021-11-30 23:03 UTC, JuanequeX commented on stylesheets/application/objects/buttons.scss
> +  margin-bottom: 3rem;
Please sort this block

2021-11-30 23:03 UTC, JuanequeX commented on stylesheets/application.scss
> +    }
solve this identation

2021-11-30 23:22 UTC, adrianMRJ commented on stylesheets/application/objects/buttons.scss
> +}
done

2021-11-30 23:22 UTC, adrianMRJ commented on stylesheets/application/objects/inputs.scss
> +}
Done

2021-11-30 23:23 UTC, adrianMRJ commented on stylesheets/application/objects/labels.scss
> +}
Done

2021-11-30 23:25 UTC, adrianMRJ commented on stylesheets/application/typography.scss
> +}
Done

2021-11-30 23:28 UTC, adrianMRJ commented on stylesheets/application/objects/buttons.scss
> +  margin-bottom: 3rem;
Done

2021-11-30 23:29 UTC, adrianMRJ commented on stylesheets/application.scss
> +    }
done

2021-11-30 23:37 UTC, JuanequeX approved these changes
LGTM

2021-12-01 00:20 UTC, jestradadeveloper approved these changes
LGTM

2021-12-01 00:22 UTC, merged